[project]
name = "ai-shop-helper-backend"
version = "0.1.0"
description = "Backend for AI Shop Helper"
authors = [
    { name = "Cristian Davis", email = "cristian.davis@sandsdev.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.18.4",
    "fastapi[standard]>=0.128.0",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.3",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.11.0",
    "sqlmodel>=0.0.37",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.14.10",
    "ty>=0.0.19",
]

[tool.ruff.lint]
extend-select = ["I", "ANN", "UP"]

[tool.ruff.lint.per-file-ignores]
"!src/**.py" = ["ANN"]

[tool.pytest]
addopts = ["-raq", "--cov=src", "--cov-report=term-missing"]
testpaths = ["tests"]
anyio_mode = "auto"

[tool.coverage.report]
exclude_lines = ["pass"]

[tool.alembic]
script_location = "%(here)s/migrations"
prepend_sys_path = [
    "."
]
