"""make refresh token unique

Revision ID: bb116d06676a
Revises: 4b264fb95f0a
Create Date: 2026-03-03 17:56:55.138016
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'bb116d06676a'
down_revision: str | Sequence[str] | None = '4b264fb95f0a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtoken_token'), table_name='refreshtoken')
    op.create_index(op.f('ix_refreshtoken_token'), 'refreshtoken', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtoken_token'), table_name='refreshtoken')
    op.create_index(op.f('ix_refreshtoken_token'), 'refreshtoken', ['token'], unique=False)
    # ### end Alembic commands ###
